# Generated by Django 2.0.2 on 2018-03-02 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='test',
            new_name='text',
        ),
    ]
